# Generated by Django 3.1.1 on 2020-09-26 12:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='requirementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_name', models.CharField(max_length=20)),
                ('product_Image', models.TextField()),
                ('product_description', models.TextField()),
                ('product_max_quantity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('Category', models.CharField(choices=[('Medicines', 'Medicines'), ('Ventilators', 'Ventilators'), ('Beds', 'Beds'), ('Other', 'Other'), ('GR', 'Graduate')], default='Medicines', max_length=20)),
                ('admin_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
