# Generated by Django 3.1.1 on 2020-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0003_remove_requirementmodel_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementmodel',
            old_name='admin_name',
            new_name='admin',
        ),
    ]
