# Generated by Django 3.1.1 on 2020-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0006_auto_20200927_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='doner_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='product_id',
            field=models.CharField(max_length=20),
        ),
    ]
