# Generated by Django 3.1.1 on 2020-09-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0008_auto_20200927_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='product_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='quantity_donated',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
